services:
  - type: web
    name: esg-dashboard
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: NEWS_API_KEY
        value: your_api_key_here
    plan: free
